### ISSUE TITLE
Not explicitly free software

### ISSUE THREAD

**Issue by nckx** [alphabetum/hosts#10]
Thanks for (presumably) releasing this under a free licence!

Unfortunately, there's no indication in `hosts` that it's free software, or that the `LICENSE` file here applies to it.  This is particularly problematic as users are encouraged to copy/curl it as a stand-alone script.

The short text of `LICENSE` should be included verbatim as a comment in the script itself, under the copyright notice.

**Comment by xwmx** [comment]
Thanks for the heads up! I added the license text to the script header as requested.

**Comment by nckx** [comment]
That was impressively fast.  Thank you!
