### ISSUE TITLE
Package on AUR for Arch Linux users

### ISSUE THREAD

**Issue by clintval** [alphabetum/hosts#3]
Hi @alphabetum great utility! Not an issue, just wanted to give you a heads up.

I created and maintain the package for `hosts` on the AUR:

https://aur.archlinux.org/packages/hosts/

Arch Linux users can install and upgrade with their package managers now.

**Comment by xwmx** [comment]
Awesome! I added a link to the AUR package in README.md. Thanks, @clintval !! 😄
