### ISSUE TITLE
bugs when executing outside of path

### ISSUE THREAD

**Issue by treehousetim** [alphabetum/hosts#8]
I have included the script in a project directory where it is called from a project setup shell script.

Because of this line, on/around line 241, the internal recursive calls to itself fail.
`_ME=$(basename "${0}")`

This may not be the most elegant fix for it, but this works.

`_ME=$(cd "$(dirname "$0")"; pwd)/$(basename "${0}")`

This is because the script is trying to call itself without a path.

**Comment by xwmx** [comment]
Thanks for the heads up! I went ahead and modified everything to not rely on the `hosts` executable being in `$PATH`, so it should now work for you as of version 3.2.5

Let me know if you run into additional issues with this!
